name: publish-to-github-pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install dependencies
      - name: Install dependencies 📦
        run: npm ci

      # 4️⃣ Create .env file
      - name: Create .env file 📝
        run: |
          touch .env
          echo TINA_TOKEN=${{ secrets.TINA_TOKEN }} >> .env
          echo NEXT_PUBLIC_TINA_CLIENT_ID=${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }} >> .env

      # 5️⃣ Build Next.js site
      - name: Build Next.js 🏗️
        run: npm run build

      # 6️⃣ Configure GitHub Pages
      - name: Setup Pages ⚙️
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      # 7️⃣ Upload artifact
      - name: Upload artifact 📡
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
